Extract NqtInAcademicYearAfterIttForm
DFE-Digital/claim-additional-payments-for-teaching pull request #2663
Opened 2024-04-04 09:44 UTC by rjlynch

Please feel free to nit pick as much as possible!

I changed the `Journeys::Base` class to allow sub classes to define what forms are available.
I'm pretty sure there's a nicer DSLy way of doing this but I didn't want to change the base class too much while others are working on it.
It didn't seem like the `nqt-in-academic-year-after-itt` step is shared so I put the form for that in the additional payments for teaching journey - I could be wrong about this.

I'm unsure about the backlink path piece, I've kept the logic for rendering that the same as it was in the claim controller. I think it could be simplified and we could remove `return unless page_sequence.in_sequence?("correct-school")` if we can assume that `nqt-in-academic-year-after-itt` always follows the `correct-school` step - I'm not sure on that assumption though.

I hope the specs are ok! For the past year or so I've been writing specs avoiding using `let` and `before` entirely and just repeating the test setup in each `it` block, which I've found works really well, so I'm a bit rusty on `let` best practices.

![walk-through](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/assets/9936028/e46bf135-902b-43d5-a2c0-c7aee0cb7657)

---
Extracts a new form object and moves the logic associated with the
`nqt_in_academic_year_after_itt` step out of claims controller into the
form.
The view no longer needs to worry about the `eligibility` attributes
being nested, so it has been updated to remove the eligibility
namespacing on fields.

I'm not stoked about having to call url helpers in the form model for
the backlink path but was unsure how else to do this. Maybe we want to
consider introducing a new object `BacklinkPath` and pass the form
object to that? Something like
```
BacklinkPath.new(form).to_s #=> "/the-path/we/want"
```

Also I think if we're going to keep the permitting params logic in the
form object, we'll probably want to make it a bit more ergonomic to
define what params are permitted. We could add a class attribute to the
base form and then child forms could do something like
```
class SomeForm < Form
  permitted_params %i[some_param]
```
or we could just read off the attributes defined on the form and assume
any defined attribute is safe to permit as a paramerter.

We could also now remove the validation for
`:nqt_in_academic_year_after_itt` from
`Policies::EarlyCareerPayments::Eligibility` as it's no longer needed,
though I've left this in place for the time being, something for a
future commit.

2024-04-04 14:06 UTC, slorek requested changes
Thanks for getting through this so quickly. Generally the approach looks good to me.

To pick up on some of your points:

* I think keeping the backling path logic as currently is right; this needs some further thought. I would expect the `PageSequence` class to be best placed to tell us what the back link would be.
* I don't have a strong preference on the style of use of `let` and `before` but where it makes sense is to reduce duplication in the tests. I can see a few opportunities to refactor the spec to reduce duplication. I think pretty soon we will develop a 'template' spec which can be used as a skeleton for new form objects so it would be godo to agree a consistent style here as there will be so many, and we don't want the testing style to be too different.
* Please do remove the model validation in the eligibility class as that's one of the main benefits of doing this work and will help us for the next phase of refactoring.

2024-04-04 14:06 UTC, slorek commented on spec/forms/nqt_in_academic_year_after_itt_form_spec.rb
> +            let(:claim) do
Can we use a factory for this please? As the data schema changes this will require continual maintenence.

2024-04-04 14:24 UTC, rjlynch commented on app/forms/nqt_in_academic_year_after_itt_form.rb
> +  end
Need this so the form builder doesn't try to make a post request when being submitted and instead uses a patch request.
Previously the form builder was passed a Claim record which was `persisted? #=> true` but we want to pass the form object to the form builder so we need to define `persisted?` ourselves
```
- <%= form_for current_claim, url: path_for_form do |form| %>
+ <%= form_for @form, url: path_for_form do |f| %>
```

we probably want to move `persisted?` into the base form class as, I think, we always want to hit the `update` action in the claims controller.

Other option is to set `method: :patch` on all the form builders calls but I think that's worse / easy to over look

2024-04-04 14:26 UTC, rjlynch commented on app/models/journeys/additional_payments_for_teaching.rb
> +    end
Run into load order issues using a const here. Not sure what a better option is tbh.

2024-04-04 14:27 UTC, rjlynch commented on app/forms/nqt_in_academic_year_after_itt_form.rb
> +  end
👍 that will let us delete some test cases too

2024-04-04 14:29 UTC, rjlynch commented on app/forms/nqt_in_academic_year_after_itt_form.rb
> +  end
I agree, I'm overly cautious about moving stuff into base classes though 😂 
Will move this up along with the `persisted?` method

2024-04-05 13:33 UTC, rjlynch commented
Closing this an reopening a pr that's not from a fork so ci runs

2024-04-05 13:33 UTC, closed without merging