[LUPEYALPHA-559] Introduce further education payments
DFE-Digital/claim-additional-payments-for-teaching pull request #2893
Opened 2024-06-20 15:25 UTC by asmega

# Context

- https://dfedigital.atlassian.net.mcas.ms/browse/LUPEYALPHA-559
- Introduce further education payments journey into the application
- We want to add scaffolding for this journey to unblock developers so they can start working in parallel  

# Changes

- Added lots of boilerplate to enable new FE payments journey
- Simple test to go through happy path journey pages
- Added lots of place holder pages with blank content to be added later

# Know issues

- There are multiple issues with this PR but have left out of scope of this PR
- Back links don't work
- Only added single happy path, many branching pages will be missing
- There is no form submission at the end and will still need implementing

2024-06-20 16:07 UTC, rjlynch requested changes
Overall LGTM but looks like the eligibility model has snuck into the module definition

2024-06-20 16:07 UTC, rjlynch commented on app/models/policies/further_education_payments.rb
> +    end
```suggestion
```
Should this be here?

2024-06-20 16:15 UTC, asmega commented on app/models/policies/further_education_payments.rb
> +    end
oh yeah good spot

2024-06-21 14:57 UTC, rjlynch approved these changes
Looks good 👍

2024-06-21 15:14 UTC, merged