[LUPEYALPHA-934] FE LUP name change
DFE-Digital/claim-additional-payments-for-teaching pull request #3138
Opened 2024-08-29 15:58 UTC by alkesh

new name for FE LUP: 
> Targeted retention incentive payments for FE teachers

2024-08-30 08:28 UTC, alkesh commented on app/views/further_education_payments/provider/claims/complete.html.erb
this page is not in the Figma

2024-08-30 08:51 UTC, rjlynch approved these changes
Looks good 👍

2024-08-30 14:08 UTC, slorek requested changes

2024-08-30 14:08 UTC, slorek commented on app/views/further_education_payments/claims/_ineligible_courses.html.erb
> +      For more information, check the eligibility criteria for <%= govuk_link_to "levelling up premium payments for early career further education teachers", t("further_education_payments.eligibility
```suggestion
      For more information, check the eligibility criteria for <%= govuk_link_to "targeted retention incentive payments for early career further education teachers", t("further_education_payments.eligibility_criteria_link_url"), new_tab: true %>.
```

2024-08-30 14:08 UTC, slorek commented on app/views/further_education_payments/claims/_ineligible_fe_provider.html.erb
> +      For more information, check the eligibility criteria for <%= govuk_link_to "levelling up premium payments for early career further education teachers", t("further_education_payments.eligibility
```suggestion
      For more information, check the eligibility criteria for <%= govuk_link_to "targeted retention incentive payments for early career further education teachers", t("further_education_payments.eligibility_criteria_link_url"), new_tab: true %>.
```

2024-08-30 14:08 UTC, slorek commented on app/views/further_education_payments/claims/_ineligible_lack_teaching_responsibilities.html.erb
> +      For more information, check the eligibility criteria for <%= govuk_link_to "levelling up premium payments for early career further education teachers", t("further_education_payments.eligibility
```suggestion
      For more information, check the eligibility criteria for <%= govuk_link_to "targeted retention incentive payments for early career further education teachers", t("further_education_payments.eligibility_criteria_link_url"), new_tab: true %>.
```

2024-08-30 14:08 UTC, slorek commented on app/views/further_education_payments/claims/_ineligible_lacks_teacher_qualification_or_enrolment.html.erb
> +      For more information, check the eligibility criteria for <%= govuk_link_to "levelling up premium payments for early career further education teachers", t("further_education_payments.eligibility
```suggestion
      For more information, check the eligibility criteria for <%= govuk_link_to "targeted retention incentive payments for early career further education teachers", t("further_education_payments.eligibility_criteria_link_url"), new_tab: true %>.
```

2024-08-30 14:08 UTC, slorek commented on app/views/further_education_payments/claims/_ineligible_less_than_half_hours_teaching_eligible_courses.html.erb
> +      For more information, check the eligibility criteria for <%= govuk_link_to "levelling up premium payments for early career further education teachers", t("further_education_payments.eligibility
```suggestion
      For more information, check the eligibility criteria for <%= govuk_link_to "targeted retention incentive payments for early career further education teachers", t("further_education_payments.eligibility_criteria_link_url"), new_tab: true %>.
```

2024-08-30 14:08 UTC, slorek commented on app/views/further_education_payments/claims/_ineligible_must_at_least_half_hours_teaching_fe.html.erb
> +      For more information, check the eligibility criteria for <%= govuk_link_to "levelling up premium payments for early career further education teachers", t("further_education_payments.eligibility
```suggestion
      For more information, check the eligibility criteria for <%= govuk_link_to "targeted retention incentive payments for early career further education teachers", t("further_education_payments.eligibility_criteria_link_url"), new_tab: true %>.
```

2024-08-30 14:08 UTC, slorek commented on app/views/further_education_payments/claims/_ineligible_must_be_recent_further_education_teacher.html.erb
> +      For more information, check the eligibility criteria for <%= govuk_link_to "levelling up premium payments for early career further education teachers", t("further_education_payments.eligibility
```suggestion
      For more information, check the eligibility criteria for <%= govuk_link_to "targeted retention incentive payments for early career further education teachers", t("further_education_payments.eligibility_criteria_link_url"), new_tab: true %>.
```

2024-08-30 14:08 UTC, slorek commented on app/views/further_education_payments/claims/_ineligible_must_teach_at_least_one_term.html.erb
> +      For more information, check the eligibility criteria for <%= govuk_link_to "levelling up premium payments for early career further education teachers", t("further_education_payments.eligibility
```suggestion
      For more information, check the eligibility criteria for <%= govuk_link_to "targeted retention incentive payments for early career further education teachers", t("further_education_payments.eligibility_criteria_link_url"), new_tab: true %>.
```

2024-08-30 14:08 UTC, slorek commented on app/views/further_education_payments/claims/_ineligible_subject.html.erb
> +      For more information, check the eligibility criteria for <%= govuk_link_to "levelling up premium payments for early career further education teachers", t("further_education_payments.eligibility
```suggestion
      For more information, check the eligibility criteria for <%= govuk_link_to "targeted retention incentive payments for early career further education teachers", t("further_education_payments.eligibility_criteria_link_url"), new_tab: true %>.
```

2024-08-30 14:08 UTC, slorek commented on app/views/further_education_payments/claims/_ineligible_subject_to_problematic_actions.html.erb
> +      For more information, check the eligibility criteria for <%= govuk_link_to "levelling up premium payments for early career further education teachers", t("further_education_payments.eligibility
```suggestion
      For more information, check the eligibility criteria for <%= govuk_link_to "targeted retention incentive payments for early career further education teachers", t("further_education_payments.eligibility_criteria_link_url"), new_tab: true %>.
```

2024-08-30 14:08 UTC, slorek commented on app/views/further_education_payments/claims/_ineligible_teaching_less_than_2_5.html.erb
> +      For more information, check the eligibility criteria for <%= govuk_link_to "levelling up premium payments for early career further education teachers", t("further_education_payments.eligibility
```suggestion
      For more information, check the eligibility criteria for <%= govuk_link_to "targeted retention incentive payments for early career further education teachers", t("further_education_payments.eligibility_criteria_link_url"), new_tab: true %>.
```

2024-08-30 14:08 UTC, slorek commented on app/views/further_education_payments/claims/_ineligible_teaching_less_than_2_5_next_term.html.erb
> +      For more information, check the eligibility criteria for <%= govuk_link_to "levelling up premium payments for early career further education teachers", t("further_education_payments.eligibility
```suggestion
      For more information, check the eligibility criteria for <%= govuk_link_to "targeted retention incentive payments for early career further education teachers", t("further_education_payments.eligibility_criteria_link_url"), new_tab: true %>.
```

2024-08-30 14:08 UTC, slorek commented on app/views/further_education_payments/claims/eligible.html.erb
> +        For more information about why you are eligible, read about the <%= govuk_link_to "levelling up premium payments for early career further education teachers", t("further_education_payments.el
```suggestion
        For more information about why you are eligible, read about the <%= govuk_link_to "targeted retention incentive payments for early career further education teachers", t("further_education_payments.eligibility_criteria_link_url"), new_tab: true %>.
```

2024-08-30 14:08 UTC, slorek commented on app/views/further_education_payments/landing_page.html.erb
> +      Further information about the eligibility criteria can be found in the <%= govuk_link_to "levelling up premium payments for FE teachers guidance", t("further_education_payments.eligibility_crit
```suggestion
      Further information about the eligibility criteria can be found in the <%= govuk_link_to "targeted retention incentive payments for FE teachers guidance", t("further_education_payments.eligibility_criteria_link_url"), target: "_blank" %>.
```

2024-09-03 15:55 UTC, slorek approved these changes

2024-09-04 10:53 UTC, merged